version: '1'
services:
  web:
    build: .
    ports:
      - 80:4200
    environment:
      - MONGO_URI=mongodb://db:27017/test
  db:
    image: "mongo" 
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
